packages:
  - apps/*
  - packages/*
catalog:
  '@antfu/eslint-config': ^4.16.1
  '@unocss/eslint-plugin': ^66.2.3
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@commitlint/cz-commitlint': ^19.8.1
  '@commitlint/types': ^19.8.1
  '@types/postcss-import': ^14.0.3
  '@unocss/eslint-config': ^66.2.3
  '@vitest/coverage-v8': ^3.2.4
  '@vue/test-utils': ^2.4.6
  '@types/node': ^24.0.3
  shx: ^0.4.0
  '@vitejs/plugin-vue': ^5.2.4
  assert: ^2.1.0
  bumpp: ^10.1.1
  conventional-changelog-cli: ^5.0.0
  eslint: ^9.28.0
  eslint-plugin-vue: ^10.1.0
  eslint-config-turbo: ^2.5.4
  fflate: ^0.8.2
  hash-sum: ^2.0.0
  lint-staged: ^16.1.0
  prettier: ^3.5.3
  simple-git-hooks: ^2.13.0
  sucrase: ^3.35.0
  typescript: ^5.8.3
  typescript-eslint: ^8.33.1
  vite: ^6.3.5
  vite-plugin-dts: ^4.5.4
  vue: ^3.5.16
  autoprefixer: ^10.4.21
  commitizen: ^4.3.1
  cz-conventional-changelog: ^3.3.0
  cross-env: ^7.0.3
  eslint-config-prettier: ^9.1.0
  eslint-plugin-cypress: ^3.6.0
  eslint-plugin-format: ^1.0.1
  husky: ^9.1.7
  stylelint: ^16.19.1
  stylelint-config-html: ^1.1.0
  stylelint-config-hudochenkov: ^10.0.0
  stylelint-config-prettier-scss: ^1.0.0
  stylelint-config-standard: ^36.0.1
  stylelint-order: ^6.0.4
  stylelint-scss: ^6.12.0
  unocss: ^66.2.3
  vitest: ^3.2.4
  vue-tsc: ^2.2.10
  postcss: ^8.5.3
  postcss-html: ^1.8.0
  postcss-import: ^16.1.0
  postcss-scss: ^4.0.9
  eslint-plugin-turbo: ^2.5.4
  bunchee: ^6.4.0
  turbo: ^2.5.4
  tsup: ^8.5.0
  express: ^5.1.0
  '@types/express': ^5.0.3
  cors: ^2.8.5
  '@types/cors': ^2.8.19
  morgan: ^1.10.0
  '@types/morgan': ^1.9.10
  supertest: ^7.1.1
  '@types/supertest': ^6.0.3
  jsdom: ^26.1.0
  'happy-dom': ^18.0.1
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - simple-git-hooks
